language: generic
sudo: required
servides:
    - docker

before_install:
    - docker build -t maxwellpereira/docker-react -f  Dockerfile.dev .

script:
  - docker run maxwellpereira/docker-react npm run test -- --coverage
