language: node_js
sudo: required
servides:
    - docker

before_install:
    - docker build -t maxwellpereira/docker-react -f  Dockerfile.dev .

script:
  - docker run -e CI=true maxwellpereira/docker-react npm run test
